version: "3.8"

services:
  cloudmart-api:
    build: ..
    ports:
      - "8000:80"
    environment:
      - COSMOS_ENDPOINT=${https://cloudmart-db-nmohammadiafshar.documents.azure.com:443/}
      - COSMOS_KEY=${D3wbRpOZsfObmCqnrRljdaelGv4J9CTDhIOAfAfzKwbxhCflrKGfCnBnd6LGHcjC2DwmTNK2KGZ9ACDbgUYJNw==}
      - COSMOS_DB_NAME=cloudmart
